### ISSUE TITLE
[Question] Templates for the SquadShifts datasets

### ISSUE THREAD

**Issue by kykim0** [BatsResearch/nayak-arxiv24-code#4]
Hello!

I was curious if the templates used for the SquadShifts datasets have not been committed yet, or if I'm missing something.

Thanks,

**Comment by nihalnayak** [comment]
Thanks for the issue. I am using Squadshifts templates from P3 (https://github.com/bigscience-workshop/promptsource/tree/main/promptsource/templates/squadshifts). 
https://github.com/BatsResearch/nayak-aclfindings24-code/blob/d185657f7f1db15093ee97854919b9661a615d65/evaluation/merge_and_evaluate_squad.py#L170-L173

Since this did not have reddit, we used the amazon template and replaced "amazon" with "reddit" in one of the templates. Hope this helps.

**Comment by kykim0** [comment]
Thanks for the reply. I overlooked that the a separate eval script is used for those templates. Thanks!
